[toolchain]
anchor_version = "0.32.1"
solana_version = "2.2.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
hope_rise = "BAaDjLVffrtNzgKLoUjmM9t1tWBHxMF6UFdnL1NYmQ3J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
